---
- hosts: #HOSTS
  name: Verificador de software minimo
  become: yes
  tasks:

    - name: anadiendo repo vscode
      shell:
        cmd: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg ;sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ ;rm /etc/apt/sources.list.d/vscode.list 2> /dev/null ; sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
        
    - name: Updateando repositorios
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: instalando vscode
      apt: 
        name: code

    - name: Instalacion de paquetes esenciales
      apt: name={{ item }}
      loop: [ 'build-essential', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python-pip', 'python3-setuptools', 'python-setuptools', 'htop', 'terminator', 'vim', 'emacs', 'aptitude']

    - name: Instalacion de CodeBlocks
      apt:
        name: codeblocks
        state: present

    - name: Instalacion de Default JDK - JRE (Java)  
      apt: name={{ item }}
      loop: [ 'default-jre', 'default-jdk' ]

    - name: Instalacion de GIT
      apt:
        name: git

    - name: Instalacion de R
      apt: name={{ item }}
      loop: [ 'r-base', 'r-base-dev' ]

    - name: Instalacion de fail2ban
      apt:
        name: fail2ban

        #- name: instalando IDLE (vscode)
        #shell:
        #cmd: dpkg -i /tmp/code*.deb
    
    - name: Instalacion de Haskell
      apt:
        name: haskell-platform

    - name: Instalacion de Prolog
      apt:
        name: swi-prolog

    - name: Instalacion de Haskell
      apt:
        name: haskell-platform

    - name: Upgradear todos los paquetes de forma segura
      apt:
        upgrade: safe

    - name: Limpiar la cache de los paquetes inutiles
      apt:
        autoclean: yes
